# Navigation links
navigation:
  - name: "HOME"
    url: "/"
  - name: "PEOPLE"
    url: "/people.html"
  - name: "THIS SEMESTER"
    url: "/thissemester.html"
  - name: "PORTFOLIO"
    url: "/portfolio.html"
  - name: "CONTACT"
    url: "/contact.html"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"