# config.yml

# Global Settings
global:
  site_name: "p-ai"
  base_url: "https://asyalyu.github.io/pai/"
  default_language: "en"
  
  # Build Settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation Menu (Toolbar)
navigation:
  - name: "Home"
    url: "/"
    icon: "home"
    visible: true

  - name: "About"
    url: "/about/"
    icon: "info"
    visible: true

  # Exclude Files/Folders from Build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md